version: "3"
services:

  postgres:
    image: library/postgres:13
    container_name: postgres
    restart: on-failure
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: postgres
    volumes:
      - db-data:/var/lib/postgresql/data
      - ./postgres/:/docker-entrypoint-initdb.d/
    ports:
      - "5432:5432"

  app:
    image: cpr4z/lab1-disp:latest
    depends_on:
      - postgres
    ports:
      - "8080:8080"
    command:
      [
        "sh", "-c",
        "chmod +x /myproject/src/build/person_backend/person_backend && /myproject/src/build/person_backend/person_backend '/myproject/src/person_backend/persons.yaml'"
      ]
    environment:
      - TZ=Europe/Moscow

volumes:
  db-data: