FROM docker.io/cpr4z/lab1-rsoi:latest

COPY ./ /persons
EXPOSE 8080

ENV PORT=8080

ENV CXX=/usr/bin/g++-10

RUN cd persons && \
    cmake -DCMAKE_CXX_COMPILER=$CXX -DCMAKE_CXX_FLAGS="-fcoroutines" -S . -Bbuild && \
    cmake --build build --target all -- -j $(nproc) && \
    cd /

CMD ["/persons/build/person_backend", "/persons/person_backend/persons.yml"]