name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    container: cpr4z/lab1-rsoi

    steps:
      - uses: actions/checkout@v2
      - name: Set up job container
        uses: addnab/docker-run-action@v3
        with:
          image: cpr4z/lab1-rsoi
          options: --network host
      - name: build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_CXX_COMPILER=g++-10 ../src
          make -j12
      - uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: ./build

  unit_tests:
    needs: build
    runs-on: ubuntu-latest
    container: cpr4z/lab1-rsoi

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: ./build

      - name: run_unit_tests
        run: |
          cd build/persons-service/unit_tests
          chmod +x persons_ut
          ./persons_ut