name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    container: Cpr4z/lab1-rsoi

    steps:
      - uses: actions/checkout@v2
      - name: build
        run: |
          mkdir build && cd build
          cmake -DCMAKE_CXX_COMPILER=g++-10 ../src
          make -j12
      - uses: actions/upload-artifact@master
        with:
          name: build-artifact
          path: ./build

  unit_tests:
    needs: build
    runs-on: ubuntu-latest
    container: Cpr4z/lab1-RSOI

    steps:
      - uses: actions/checkout@v2
      - uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: ./build

      - name: run_unit_tests
        run: |
          cd build/persons_backend/unit_tests
          chmod +x persons_ut
          ./persons_ut

  deploy:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: ashishkujoy/render-deploy@v1.0.5
        with:
          service-id:
          service-key:
          api-key:
          max-deployment-wait-ms: 3600000
          delay-in-ms: 10000