name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
#jobs:
#  build:
#    runs-on: ubuntu-latest
#    container: cpr4z/lab1-rsoi
#
#    steps:
#      - uses: actions/checkout@v2
#      - name: build
#        run: |
#          mkdir build && cd build
#          cmake -DCMAKE_CXX_COMPILER=g++-10 ../src
#          make -j12
#      - uses: actions/upload-artifact@master
#        with:
#          name: build-artifact
#          path: ./build
#
#  unit_tests:
#    needs: build
#    runs-on: ubuntu-latest
#    container: cpr4z/lab1-rsoi
#
#    steps:
#      - uses: actions/checkout@v2
#      - uses: actions/download-artifact@master
#        with:
#          name: build-artifact
#          path: ./build
#
#      - name: run_unit_tests
#        run: |
#          cd build/persons-service/unit_tests
#          chmod +x persons_ut
#          ./persons_ut


jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v1
      - name: Login to Docker Hub
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Build and Push Docker Image
        run: |
          docker build -t cpr4z/lab1-disp -f Dockerfile .
          docker push cpr4z/lab1-disp

      - name: Copy code to Yandex VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p ~/app
      - name: Transfer files to Yandex VM
        run: scp -o StrictHostKeyChecking=no -i ~/.ssh/id_ed25519 -r ../../lab1-template/ ${{ secrets.VM_USER }}@${{ secrets.VM_HOST }}:~/app


  deploy:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Deploy to Yandex VM
        uses: appleboy/ssh-action@v0.1.6
        with:
          host: ${{ secrets.VM_HOST }}
          username: ${{ secrets.VM_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            cd ~/app
            docker pull cpr4z/lab1-disp
            docker-compose -f ../docker-compose.yml up -d --build