name: GitHub Classroom Workflow
on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop
jobs:
  build:
    runs-on: ubuntu-latest
    container: docker.io/cpr4z/lab1-rsoi

    steps:
      # Checkout the repository
      - uses: actions/checkout@v3

      # Build Docker image from the Dockerfile in the current directory
      - name: Build Docker image
        run: |
          docker build -t cpr4z/lab1-rsoi:latest --file ./Dockerfile .

      # Login to Docker Hub
      - name: Log in to Docker Hub
        run: |
          echo "${{ secrets.DOCKER_PASSWORD }}" | docker login -u "${{ secrets.DOCKER_USERNAME }}" --password-stdin

      # Push the Docker image to Docker Hub
      - name: Push to Docker Hub
        run: |
          docker push cpr4z/lab1-rsoi:latest

      # Start the container
      - name: Run Docker container
        run: |
          docker run -d --name lab1-rsoi -p 8080:8080 cpr4z/lab1-rsoi:latest

      # Check if container is running
      - name: Ensure container is running
        run: |
          docker ps -q --filter "name=lab1-rsoi" || exit 1

      # Build project inside the container (if applicable)
      - name: Build project inside container
        run: |
          docker exec -it lab1-rsoi mkdir build && cd build && cmake .. && make -j12

      # Upload artifact if needed (for saving build results, optional)
      - uses: actions/upload-artifact@v3
        with:
          name: build-artifact
          path: ./build

  unit_tests:
    needs: build
    runs-on: ubuntu-latest
    container: docker.io/cpr4z/lab1-rsoi

    steps:
      - uses: actions/checkout@v3
      - uses: actions/download-artifact@master
        with:
          name: build-artifact
          path: ./build

      - name: run_unit_tests
        run: |
          cd build/persons_backend/unit_tests
          chmod +x persons_ut
          ./persons_ut

  deploy:
    needs: unit_tests
    runs-on: ubuntu-latest
    steps:
      - uses: ashishkujoy/render-deploy@v1.0.5
        with:
          service-id: 45ad789b9e1676d29e7c90242a42ac91
          service-key: a05dcde78ad00a1d81ce44d388e94f04
          api-key: 5bba4fcd8d77371f811b90350a86ee81
          max-deployment-wait-ms: 3600000
          delay-in-ms: 10000